### ISSUE TITLE
gen.data.frame sometimes does not generate a data.frame

### ISSUE THREAD

**Issue by ggrothendieck** [patrickroocks/listcompr#6] opened 2021-05-20 17:30 UTC
In the following example we used gen.data.frame but it produced a matrix.

```
a <- anscombe
gen.data.frame(data.frame(empty = NA, a[i], a[i+1]), i = seq(1, ncol(a), 2), bycol = TRUE)

giving this **matrix**

      empty x1 x2 empty x3 x4 empty    y1   y2 empty    y3    y4
 [1,]    NA 10 10    NA 10  8    NA  8.04 9.14    NA  7.46  6.58
 [2,]    NA  8  8    NA  8  8    NA  6.95 8.14    NA  6.77  5.76
 [3,]    NA 13 13    NA 13  8    NA  7.58 8.74    NA 12.74  7.71
 [4,]    NA  9  9    NA  9  8    NA  8.81 8.77    NA  7.11  8.84
 [5,]    NA 11 11    NA 11  8    NA  8.33 9.26    NA  7.81  8.47
 [6,]    NA 14 14    NA 14  8    NA  9.96 8.10    NA  8.84  7.04
 [7,]    NA  6  6    NA  6  8    NA  7.24 6.13    NA  6.08  5.25
 [8,]    NA  4  4    NA  4 19    NA  4.26 3.10    NA  5.39 12.50
 [9,]    NA 12 12    NA 12  8    NA 10.84 9.13    NA  8.15  5.56
[10,]    NA  7  7    NA  7  8    NA  4.82 7.26    NA  6.42  7.91
[11,]    NA  5  5    NA  5  8    NA  5.68 4.74    NA  5.73  6.89
```

**Comment by patrickroocks** [comment] 2021-05-21 18:18
There was a bug regarding the output type of the result of `gen.data.frame` in conjunction with `byrow = TRUE` (formely `bycol`). Fixed with the last commit.

Anyway, the semantics of the old `bycol` was pretty strange... the new idea is: The inner elements (i.e., `empty`, `a[i]`) of the given vector/list (or data frame) shall be interpreted as rows.

Thus we have now (with the last commit):

    > gen.data.frame(data.frame(empty = NA, a[i], a[i+1]), i = seq(1, ncol(a), 2), byrow = TRUE)
      V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11 V1 V2 V3 V4 V5 V6 V7 V8 V9 V10 V11   V1   V2   V3   V4   V5   V6   V7   V8    V9      V10  V11   V1   V2    V3   V4   V5   V6   V7    V8   V9  V10  V11
    empty NA NA NA NA NA NA NA NA NA  NA  NA NA NA NA NA NA NA NA NA NA  NA  NA   NA   NA   NA   NA   NA   NA   NA   NA    NA   NA   NA   NA   NA    NA   NA   NA   NA   NA    NA   NA   NA   NA
    x1    10  8 13  9 11 14  6  4 12   7   5 10  8 13  9 11 14  6  4 12   7   5 8.04 6.95 7.58 8.81 8.33 9.96 7.24 4.26 10.84 4.82 5.68 7.46 6.77 12.74 7.11 7.81 8.84 6.08  5.39 8.15 6.42 5.73
    x2    10  8 13  9 11 14  6  4 12   7   5  8  8  8  8  8  8  8 19  8   8   8 9.14 8.14 8.74 8.77 9.26 8.10 6.13 3.10  9.13 7.26 4.74 6.58 5.76  7.71 8.84 8.47 7.04 5.25 12.50 5.56 7.91 6.89

Without `byrow` the inner vector is interpreted as columns and we get (note that we need `a[[i]]` instead of `a[i]` to get this work - otherwise the columns names will not match):

	> gen.data.frame(data.frame(empty = NA, a[[i]], a[[i+1]]), i = seq(1, ncol(a), 2))
	   empty    V2    V3
	1     NA 10.00 10.00
	2     NA  8.00  8.00
	3     NA 13.00 13.00
	4     NA  9.00  9.00
	5     NA 11.00 11.00
	6     NA 14.00 14.00
	7     NA  6.00  6.00
	8     NA  4.00  4.00
	9     NA 12.00 12.00
	10    NA  7.00  7.00
	11    NA  5.00  5.00
	12    NA 10.00  8.00
	13    NA  8.00  8.00
	14    NA 13.00  8.00
	[ 30 lines ommitted ]

Does this fit to your expectation?

**Comment by ggrothendieck** [comment] 2021-05-22 19:40
I am not really sure. How does one get the output in the first post in this issue but as a data frame instead of a matrix?

**Comment by patrickroocks** [comment] 2021-05-22 21:25
The output in the first post cannot be directly produced with `gen.data.frame`. The idea of this function is that the first argument is an expression giving one row of the resulting data frame when evaluated. What you do, passing a data frame with many rows, is out of the intended scope of this function. It works as long as the columns have the same names, in this case they are connected with `rbind` (or with `cbind` in case that `byrow = TRUE` is set). But it's not documented behavior and I would better not rely on this.

To reproduce your result from the first post, I would use `gen.list` to put the resulting data frames in a list and combine them with `cbind` afterwards:

	> do.call("cbind", gen.list(data.frame(empty = NA, a[i], a[i+1]), i = seq(1, ncol(a), 2)))
	   empty x1 x2 empty x3 x4 empty    y1   y2 empty    y3    y4
	1     NA 10 10    NA 10  8    NA  8.04 9.14    NA  7.46  6.58
	2     NA  8  8    NA  8  8    NA  6.95 8.14    NA  6.77  5.76
	3     NA 13 13    NA 13  8    NA  7.58 8.74    NA 12.74  7.71
	4     NA  9  9    NA  9  8    NA  8.81 8.77    NA  7.11  8.84
	5     NA 11 11    NA 11  8    NA  8.33 9.26    NA  7.81  8.47
	6     NA 14 14    NA 14  8    NA  9.96 8.10    NA  8.84  7.04
	7     NA  6  6    NA  6  8    NA  7.24 6.13    NA  6.08  5.25
	8     NA  4  4    NA  4 19    NA  4.26 3.10    NA  5.39 12.50
	9     NA 12 12    NA 12  8    NA 10.84 9.13    NA  8.15  5.56
	10    NA  7  7    NA  7  8    NA  4.82 7.26    NA  6.42  7.91
	11    NA  5  5    NA  5  8    NA  5.68 4.74    NA  5.73  6.89

Anyway this data frame is a bit strange because the column `'empty'` occurs multiple times.

**Comment by patrickroocks** [comment] 2021-05-24 08:25
After thinking a while about this, I decided that it runs counter to the intention (and also the documentation) of `gen.data.frame` to pass a data.frame with multiple rows as an inner expression. With my last commit these functions catch this and return an error:

	> gen.matrix(data.frame(empty = NA, a[[i]], a[[i+1]]), i = seq(1, ncol(a), 2), byrow = TRUE)
	 Error: the inner expression was evaluated to a data frame with 11 rows, but expected exactly one row 

Nevertheless, `gen.list` can handle data frames of arbitrary structure, i.e., the statement with `do.call("cbind", ...)` in my above post still works.

**Closed as completed** 2021-06-06 08:17 UTC
